# Default values for sgsnemu and iperf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
k8s:
  network: 10.10.10.0/24
  via: 169.254.1.1

NIC:
  interface: eth0

sgsnemu:
  automode: False
  selector: vxlan.travelping.com
  replicas: 1
  image:
    repository: ergw/sgsnemu
    tag: master_b1900328f524dd0014ba54c86754ff269aa47cf3
  pullPolicy: IfNotPresent
  listenIP: 198.18.0.2/28                     # IP of grx NIC
  remoteIP: 198.18.1.2                        # IP of Cnode grx
  imsi: 240010123456789

Nettools:
  image:
    repository: travelping/nettools
    tag: 1.7.0
    pullPolicy: IfNotPresent
  resources:
    cpu: 10m

VXLan:
  image:
    repository: openvnf/kube-vxlan-controller-agent
    tag: 2.1.0
    pullPolicy: IfNotPresent
  resources:
    cpu: 10m
