apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "sgsnemu.fullname" . }}
  labels:
    app: {{ template "sgsnemu.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: sgsnemu
      app: {{ template "sgsnemu.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "sgsnemu.name" . }}
        release: {{ .Release.Name }}
        component: sgsnemu
        {{ .Values.sgsnemu.selector }}: "true"
      annotations:
        {{ .Values.sgsnemu.selector }}/networks: {{ .Values.NIC.interface }}
    spec:
      initContainers:
      {{- if .Values.VXLan.enabled }}
      - name: vxlan-controller-agent-init
        image: {{ .Values.VXLan.image.repository }}:{{ .Values.VXLan.image.tag }}
        resources:
{{ toYaml .Values.resources.vxlanControllerAgentInit | indent 10 }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      {{- end }}
      - name: network-init
        image: {{ .Values.Nettools.image.repository }}:{{ .Values.Nettools.image.tag }}
        resources:
{{ toYaml .Values.resources.networkInit | indent 10 }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command:
        - bash
        - -c
        - |
          echo "Setting up routes... "
          ip addr add {{ .Values.sgsnemu.listenIP }} dev {{ .Values.NIC.interface }}
          ip route add {{ .Values.k8s.network }} via {{ .Values.k8s.via }}
          ip link set dev {{ .Values.NIC.interface }} mtu {{ .Values.sgsnemu.mtu }}
          ip addr show

          set -x
          # set GRO settings off
          ethtool -K {{ .Values.NIC.interface }} gro off
      containers:
      - name: sgsnemu
        image: {{ .Values.sgsnemu.image.repository }}:{{ .Values.sgsnemu.image.tag }}
        resources:
{{ toYaml .Values.resources.sgsnemu | indent 10 }}
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
        command:
        - sh
        - -c
        - |
          echo "Running sgsnemu. Type 'sgsnemu --help' for info."
          {{- if .Values.sgsnemu.automode }}
          sgsnemu --remote={{ .Values.sgsnemu.remoteIP }} --listen={{$v := .Values.sgsnemu.listenIP | split "/"}}{{$v._0}} --conf=/mnt/sgsn-test.conf --createif -t v4 --defaultroute
          {{- else }}
          echo "Running in manual mode."
          {{- end }}

        volumeMounts:
        - name: sgsnemu-config
          mountPath: /mnt/
      - name: iperf
        image: {{ .Values.Iperf.image.repository }}:{{ .Values.Iperf.image.tag }}
        resources:
{{ toYaml .Values.resources.iperfSidekick | indent 10 }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command:
        - sh
        - -c
        - |
          {{- if .Values.Iperf.automode }}
          echo "Iperf3-automode running! Pushing traffic to {{ .Values.sgsnemu.remoteIP }}."
          iperf3 -c {{ .Values.sgsnemu.remoteIP }} {{ .Values.Iperf.options }}
          {{- else }}
          echo "Running in manual mode. Type 'iperf3 --help' for info."
          {{- end }}
      {{- if .Values.VXLan.enabled }}
      - name: vxlan-controller-agent
        image: {{ .Values.VXLan.image.repository }}:{{ .Values.VXLan.image.tag }}
        resources:
{{ toYaml .Values.resources.vxlanControllerAgent | indent 10 }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      {{- end }}
      volumes:
      - name: sgsnemu-config
        configMap:
          name: {{ template "sgsnemu.fullname" . }}-configmap
