apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sgsnemu.fullname" . }}-configmap
  labels:
    app: {{ template "sgsnemu.name" . }}
    chart: {{ template "sgsnemu.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  sgsn-test.conf: |
    imsi {{ .Values.sgsnemu.config.imsi }}
    qos {{ .Values.sgsnemu.config.qos }}
    qose1 {{ .Values.sgsnemu.config.qose1 }}
    qose2 {{ .Values.sgsnemu.config.qose2 }}
    qose3 {{ .Values.sgsnemu.config.qose3 }}
    qose4 {{ .Values.sgsnemu.config.qose4 }}
    charging {{ .Values.sgsnemu.config.charging }}
    apn {{ .Values.sgsnemu.config.apn }}
    msisdn {{ .Values.sgsnemu.config.msisdn }}
    uid {{ .Values.sgsnemu.config.uid }}
    pwd {{ .Values.sgsnemu.config.pwd }}
    rai {{ .Values.sgsnemu.config.rai }}
    mstz {{ .Values.sgsnemu.config.mstz }}
    nsapi {{ .Values.sgsnemu.config.nsapi }}
